version: '2'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: es1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /Users/huangqq/soft/docker/elasticsearch/es1/data:/usr/share/elasticsearch/data
      - ./elastic:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9201:9200
    networks:
      - esnet
  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: es2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /Users/huangqq/soft/docker/elasticsearch/es2/data:/usr/share/elasticsearch/data
      - /Users/huangqq/soft/docker/elasticsearch/es2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9202:9200
   

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

