---
- name: Add Group
  group: 
      name=docker
      state=present

- name: Add User
  user: 
      name=cse 
      shell=/bin/bash
      group=docker
      state=present

- name: Add cse user to the sudoers
  copy:
      dest: "/etc/sudoers.d/cse"
      content: "cse  ALL=(ALL)  NOPASSWD: ALL"
      
- name: modify hostname
  hostname: name="{{name}}"

- name: modify hosts
  template: src=hosts.j2 dest=/etc/hosts mode=0644

# - name: Install Java
#   apt:
#       name=openjdk-8-jre-headless
#       state=present

# - name: Install docker
#   shell: curl https://releases.rancher.com/install-docker/17.03.sh | sh